### ISSUE TITLE
implement the newLogo in navbar from the ui-design folder

### ISSUE THREAD

**Issue by lazyfuhrer** [lazyfuhrer/Real-Estate-Web-App#15]

**Comment by kiran-thilak** [comment]
Can I work on this issue. Assuming you want the logo placed here.
![image](https://user-images.githubusercontent.com/8852764/194768129-48cb391e-7079-4f45-91d4-442ec654f65e.png)

**Comment by lazyfuhrer** [comment]
yes! assigning you the issue

**Comment by kiran-thilak** [comment]
![image](https://user-images.githubusercontent.com/8852764/194769712-7efcad6f-376c-4cc1-81c1-0d5961eb53c9.png)

**Comment by kiran-thilak** [comment]
@lazyfuhrer could you please review the changes.
