### ISSUE TITLE
Search filter color mode

### ISSUE THREAD

**Issue by AbhinavReddy-Dev** [lazyfuhrer/Real-Estate-Web-App#26]
The color mode for the search filter is not rendering as expected, looks like there are issues with dark/light mode toggle in the UI, I can fix them.
![Screen Shot 2022-10-09 at 5 23 22 PM](https://user-images.githubusercontent.com/33514341/194786243-aee25027-985e-4f13-9d14-660d814dc822.png)

**Comment by lazyfuhrer** [comment]
sure @AbhinavReddy-Dev

**Comment by AbhinavReddy-Dev** [comment]
Thank you, one more thing, I don't know if the tag 'hacktoberfest-accepted' is also allowed, I saw many use 'hacktoberfest2022' for the issues, I might not be completely informed about all the tags that are allowed though.

**Comment by lazyfuhrer** [comment]
yes it's allowed.
refer to the maintainers section -> https://hacktoberfest.com/participation/
