### ISSUE TITLE
Add ratings property in filters (greater the price better the rating on a scale of 5)

### ISSUE THREAD

**Issue by lazyfuhrer** [lazyfuhrer/Real-Estate-Web-App#29]

**Comment by Oceaneyes123** [comment]
I'll work on it, please assign to me

**Comment by lazyfuhrer** [comment]
Sure @Oceaneyes123

**Comment by Oceaneyes123** [comment]
![image](https://user-images.githubusercontent.com/42128868/194991298-7fa337e4-87fe-4778-a71b-2f299274ca38.png)
getting issues on set up

Steps to Reproduce issue;
1. Fork repo
2. Clone repo
3. cd to repo
4. Run ```npm install```
5. Run ```npm run dev```

**Comment by lazyfuhrer** [comment]
fixed @Oceaneyes123

**Comment by Oceaneyes123** [comment]
@lazyfuhrer , Hello, please check PR #40
