### ISSUE TITLE
Property items get bigger on hover

### ISSUE THREAD

**Issue by lazyfuhrer** [lazyfuhrer/Real-Estate-Web-App#3]
Add transition effect using chakra

**Comment by druwan** [comment]
I could make an attempt for this

**Comment by lazyfuhrer** [comment]
sure @druwan .

**Comment by druwan** [comment]
Is this too big of a scale?

<img width="882" alt="Screenshot 2022-10-09 at 16 37 46" src="https://user-images.githubusercontent.com/30087790/194762883-6e42e09e-a4da-4bbc-bcba-a3d05dc4a909.png">

**Comment by lazyfuhrer** [comment]
just a lil small and then it would be fine
