### ISSUE TITLE
Create an 'About Us' page and add content

### ISSUE THREAD

**Issue by lazyfuhrer** [lazyfuhrer/Real-Estate-Web-App#32]
Content:

Magic Properties is an Online platform to Buy or Rent top Properties in Dubai. It caters to a global market with its unique services and novel online features.
The Magic Properties design is based on rigorous research, unique product developments, and innovative initiative which has been readily accepted by users. In an attempt to best serve the users, features on the Magic Properties realty portal are constantly invented, evaluated and upgraded.
For any queries, feel free to mail us at biswasbiswarghya@gmail.com

**Comment by redxzeta** [comment]
Can i work on this

**Comment by lazyfuhrer** [comment]
sure @redxzeta
