### ISSUE TITLE
Improve the design of footer

### ISSUE THREAD

**Issue by singharyan1007** [lazyfuhrer/Real-Estate-Web-App#41]
Hi @lazyfuhrer I would like to add a more functional footer to the website. Can you assign me the issue?

**Comment by lazyfuhrer** [comment]
sure @singharyan1007

**Comment by singharyan1007** [comment]
Hi @lazyfuhrer I made a PR earlier regarding this issue. Did you review it?

**Comment by IvySaskia** [comment]
I have done on issue: lazyfuhrer/Real-Estate-Web-App#56
