### ISSUE TITLE
Want to correct some css in home page when dark-mode theme is on.

### ISSUE THREAD

**Issue by goodchai0** [lazyfuhrer/Real-Estate-Web-App#43]
![1 03](https://user-images.githubusercontent.com/79858905/195080140-18ff7ba9-93b5-42b5-8d34-f89f8322b963.png)

this text is not visible in "dark-mode".
Please assign this to me under hacktoberfest 2022. @lazyfuhrer

**Comment by lazyfuhrer** [comment]
sure @goodchai0
