### ISSUE TITLE
Update the design of footer in mobile view

### ISSUE THREAD

**Issue by lazyfuhrer** [lazyfuhrer/Real-Estate-Web-App#56]

**Comment by IvySaskia** [comment]
Hi, :)

![image](https://user-images.githubusercontent.com/41027286/195730368-b4fc9170-7ade-4014-b9bd-c3f8fc06047c.png)

This is how footer is now, how would be updated? I ask in order to take this issue.

**Comment by lazyfuhrer** [comment]
make the footer more responsive and improve it's design. right now it looks pretty bad. try to make some changes. assigning you the issue. @IvySaskia

**Comment by IvySaskia** [comment]
Mobile:
![image](https://user-images.githubusercontent.com/41027286/195747825-f18ed372-ea55-4149-a828-f346e9b4e0ae.png)

Big Screen:
![image](https://user-images.githubusercontent.com/41027286/195747916-87a47429-d6b6-413d-9035-9e5c6e276b11.png)


What do you think?
